// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManageSystem.DataBase;

namespace StudentManageSystem.Migrations
{
    [DbContext(typeof(StudentDataBase))]
    [Migration("20220511055614_AddEntityMajor")]
    partial class AddEntityMajor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("StudentManageSystem.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentType = "工科",
                            Name = "自动化学院"
                        });
                });

            modelBuilder.Entity("StudentManageSystem.Entities.Major", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MajorName")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId", "MajorName");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            MajorName = "自动化与电气类"
                        });
                });

            modelBuilder.Entity("StudentManageSystem.Entities.NaturalClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassId");

                    b.HasIndex("DepartmentId", "MajorName");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            DepartmentId = 1,
                            MajorName = "自动化与电气类"
                        });
                });

            modelBuilder.Entity("StudentManageSystem.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "2022000001",
                            Birth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassId = 1,
                            IsMale = true,
                            Name = "张三"
                        },
                        new
                        {
                            Id = "2022000002",
                            Birth = new DateTime(2001, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassId = 1,
                            IsMale = false,
                            Name = "李四"
                        },
                        new
                        {
                            Id = "2022000003",
                            Birth = new DateTime(2001, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClassId = 1,
                            IsMale = true,
                            Name = "王五"
                        });
                });

            modelBuilder.Entity("StudentManageSystem.Entities.Major", b =>
                {
                    b.HasOne("StudentManageSystem.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentManageSystem.Entities.NaturalClass", b =>
                {
                    b.HasOne("StudentManageSystem.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManageSystem.Entities.Major", "Major")
                        .WithMany()
                        .HasForeignKey("DepartmentId", "MajorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("StudentManageSystem.Entities.Student", b =>
                {
                    b.HasOne("StudentManageSystem.Entities.NaturalClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentManageSystem.Entities.NaturalClass", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
